# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macos-10.14

steps:
- script: brew install sdl2 qt@5 libslirp libarchive libepoxy
  displayName: 'Install dependencies'

- script: mkdir ${{Agent.WorkFolder}}/build
  displayName: 'Create build environment'

- script: cmake ${{Build.Repository.LocalPath}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
  displayName: 'Configure'
  
- script: make -j$(sysctl -n hw.ncpu)
  displayName: 'Make'
